name: Initialize environment
description: "Installs required build tools and prepares environment for build"

runs:
  using: "composite"
  steps:
    - name: Set up Node & NPM
      uses: actions/setup-node@v6
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install PNPM
      uses: pnpm/action-setup@v4

    - name: Install modules
      run: pnpm i
      shell: bash

    - name: Print diagnostics
      run: pnpm diagnostic
      shell: bash

    - name: Check code quality
      run: pnpm lint
      shell: bash
